name: audit test build & deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  audit:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Audit dependencies
        run: yarn audit
  test:
    needs:
      - audit
    continue-on-error: true
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          yarn install
          npx playwright install --with-deps
      - name: Run e2e tests
        run: yarn playwright test --config=e2e/playwright.config.ts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: e2e/report
          retention-days: 30
  build-and-deploy:
    needs:
      - audit
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn run build
      - name: Deploy application
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: docs
